# Generated by Django 2.2.2 on 2019-06-13 17:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='static/userlogin/images/default-img.png', upload_to='profile_image')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_cell', message='Enter a valid phone number', regex='^[1-9]{1}[0-9]{9}$')])),
                ('user_type', models.CharField(choices=[('B', 'bus_client'), ('C', 'Customer'), ('H', 'hotel_client')], default='C', max_length=2)),
                ('signedup_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
