# Generated by Django 2.2.2 on 2019-06-13 17:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_type', models.IntegerField(default=1)),
                ('costperkm', models.FloatField()),
                ('serviceno', models.IntegerField()),
                ('noseats', models.IntegerField(default=0)),
                ('start_city', models.CharField(max_length=50)),
                ('destination_city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bus_agency',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_cell', message='Enter a valid phone number', regex='^[1-9]{1}[0-9]{9}$')])),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatside', models.CharField(max_length=50)),
                ('seatno', models.IntegerField()),
                ('Bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_booking.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='Bus_Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('bus_type', models.IntegerField(default=1)),
                ('journeydate', models.DateField()),
                ('journeytime', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)])),
                ('reachdate', models.DateField()),
                ('reachtime', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)])),
                ('serviceno', models.IntegerField()),
                ('booking_id', models.CharField(max_length=10)),
                ('seatno', models.CharField(max_length=5)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_booking.Bus_agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_booking.Bus_agency'),
        ),
    ]
