# Generated by Django 2.2.2 on 2019-06-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='Bus_model',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='Bus_type',
            field=models.IntegerField(choices=[('2', 'Sleeper'), ('1', 'Normal')], default=1),
        ),
    ]
