# Generated by Django 2.2.2 on 2019-06-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0003_auto_20190617_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Bus_model',
            field=models.CharField(choices=[('scania', 'scania'), ('volvo', 'volvo'), ('Normal', 'Normal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='Bus_type',
            field=models.CharField(choices=[('Sleeper', 'Sleeper'), ('Normal', 'Normal')], max_length=20),
        ),
    ]
