# Generated by Django 2.2.2 on 2019-07-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0009_auto_20190703_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='via',
            name='journeytime',
            field=models.IntegerField(null=True),
        ),
    ]
