# Generated by Django 2.2.2 on 2019-07-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0010_auto_20190705_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_booking',
            name='email',
            field=models.EmailField(default='koushiks666@gmail.com', max_length=254),
        ),
    ]
