# Generated by Django 2.2.2 on 2019-07-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0010_via_journeytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_dates',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
