# Generated by Django 2.2.2 on 2019-07-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0011_auto_20190705_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='journeytime',
            field=models.IntegerField(null=True),
        ),
    ]
