# Generated by Django 2.2.2 on 2019-07-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0011_bus_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_booking',
            name='fare',
            field=models.FloatField(default='1000.0'),
        ),
    ]
