# Generated by Django 2.2.2 on 2019-07-07 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0012_bus_booking_fare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
