# Generated by Django 2.2.2 on 2019-06-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
