# Generated by Django 2.1 on 2019-07-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0004_auto_20190705_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_booking',
            old_name='hotel_id',
            new_name='hotel',
        ),
        migrations.AddField(
            model_name='hotel_booking',
            name='room_fac',
            field=models.CharField(default='Non-AC', max_length=8),
        ),
        migrations.AlterField(
            model_name='hotel_booking',
            name='booking_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel_booking',
            name='fromtime',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel_booking',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel_booking',
            name='room_type',
            field=models.CharField(default='Room', max_length=30),
        ),
        migrations.AlterField(
            model_name='hotel_booking',
            name='totime',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_fac',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], default='Non-AC', max_length=8),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('Room', 'Room'), ('Standard Double Room', 'Standard Double Room'), ('Standard Family Room', 'Standard Family Room'), ('Deluxe Double Room', 'Deluxe Double Room')], default='Room', max_length=30),
        ),
    ]
