# Generated by Django 2.2 on 2019-06-26 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0005_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel_booking.Hotels'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/hotels'),
        ),
    ]
