# Generated by Django 2.2 on 2019-07-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0008_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='description',
            field=models.CharField(default='Hello', max_length=1000),
        ),
    ]
