# Generated by Django 2.1 on 2019-07-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0003_auto_20190619_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='pic',
            field=models.ImageField(default='places/default.jpg', upload_to='places'),
        ),
    ]
