# Generated by Django 2.1 on 2019-07-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0006_auto_20190708_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='city',
            field=models.CharField(default='hyderabad', max_length=1000),
        ),
    ]
