# Generated by Django 2.1 on 2019-07-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0007_trip_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='start_date',
        ),
    ]
