# Generated by Django 2.1 on 2019-07-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0008_remove_trip_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='days',
            field=models.CharField(max_length=1000),
        ),
    ]
